language: python
python:
  - 3.8
before_install:
  - sudo apt-get install -y csound
install:
  - pip3 install .
  - pip3 install pytest
  - pip3 install coveralls
script:
  - coverage run --source=cyscore setup.py test
after_success:
  - coveralls
